language: python
sudo: true
python:
  - "2.7"
  - "3.4"

services:
  - mongodb

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - ./test/setup_test.sh

script:
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.
  # Code static analysis
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_backend_client/*
  - rm -fr alignak_backend_client/__pycache__
  - pylint --rcfile=.pylintrc alignak_backend_client/*
  - pep257 --select=D300 alignak_backend_client
  # Code test and dynamic analysis
  - cd test
  - coverage erase
  - nosetests -xv --nologcapture --process-restartworker --processes=1 --process-timeout=300 --with-coverage --cover-package=alignak_backend_client test*.py
  - coverage report
  # Test code static analysis
  - pep8 --max-line-length=100 --ignore='E402' test_*.py
  - pylint --rcfile=../.pylintrc test_*.py
  - cd ..
after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
